### ISSUE TITLE
Encontro 2 : 08/09

### ISSUE THREAD

**Issue by Fabrycio-Nakano** [Data-Analytical-Thinking/Projeto_FMF#3]
- Análise do problema
- Exploração de possíveis alternativas
- Criação de subgrupos

**Comment by omatheusbrandao** [comment]
Análise do Problema: prever se um cliente vai sair da base do Banco ou não, ou seja, fazer uma previsão probabilística de churn para cada cliente e facilitar o atendimento ao mesmo para evitar esse problema.

**Comment by omatheusbrandao** [comment]
Subgrupo 1: Matheus Brandão e Fabrycio Leite ( análise da possibilidade de substituição do algoritmo de gradiente XgBoost pelo Light Gradient Boosting Machine e analisar se os resultados são favoráveis)

**Comment by victoremanuelgo** [comment]
Subgrupo 2: Victor e Maykon. Explorar os dados e gerar resultados visualizáveis para compreender o dataset

**Comment by MaykonAdriell** [comment]
We are together.

**Comment by MaykonAdriell** [comment]
Concluído.
