### ISSUE TITLE
Implementação de métrica AUC.  

### ISSUE THREAD

**Issue by MaykonAdriell** [Data-Analytical-Thinking/Projeto_FMF#9]
Entender consonância da métrica AUC com o modelo proposto.    
Curvas AUC e ROC estão entre as medições mais utilizadas para a avaliação de um modelo de Machine Learning .
A curva AUC é então derivada da curva ROC. 
A curva ROC já é implementada no modelo, mas não a AUC. Busca-se, portanto, meios de desenvolver tal métrica no código.

**Comment by omatheusbrandao** [comment]
Vou entrar em contato contigo para analisarmos isso!

**Comment by victoremanuelgo** [comment]
Acho que já conseguiram a solução, mas talvez isso complemente ainda mais: 

https://medium.com/kunumi/m%C3%A9tricas-de-avalia%C3%A7%C3%A3o-em-machine-learning-classifica%C3%A7%C3%A3o-49340dcdb198
